Repository kubeedge/website, pull requests merged in 2020-08, with the labels that each got.

#76 Localize css js
  data/assets.toml
  layouts/partials/footer.html
  layouts/partials/header.html
  static/cdnjs.cloudflare.com/css/academicons.min.css
  static/cdnjs.cloudflare.com/css/all.css
  static/cdnjs.cloudflare.com/css/bootstrap.min.css
  static/cdnjs.cloudflare.com/css/bootstrap.min.css.map
  static/cdnjs.cloudflare.com/css/default.min.css
  static/cdnjs.cloudflare.com/css/instantsearch-theme-algolia.min.css
  static/cdnjs.cloudflare.com/css/instantsearch.min.css
  static/cdnjs.cloudflare.com/css/jquery.fancybox.min.css
  static/cdnjs.cloudflare.com/css/leaflet.css
  static/cdnjs.cloudflare.com/js/MathJax.js
  static/cdnjs.cloudflare.com/js/anchor.min.js
  static/cdnjs.cloudflare.com/js/autotrack.js
  static/cdnjs.cloudflare.com/js/bootstrap.min.js
  static/cdnjs.cloudflare.com/js/bootstrap.min.js.map
  static/cdnjs.cloudflare.com/js/fuse.min.js
  static/cdnjs.cloudflare.com/js/gmaps.min.js
  static/cdnjs.cloudflare.com/js/highlight.min.js
  static/cdnjs.cloudflare.com/js/imagesloaded.pkgd.min.js
  static/cdnjs.cloudflare.com/js/instantsearch.min.js
  static/cdnjs.cloudflare.com/js/isotope.pkgd.min.js
  static/cdnjs.cloudflare.com/js/jquery.fancybox.min.js
  static/cdnjs.cloudflare.com/js/jquery.mark.min.js
  static/cdnjs.cloudflare.com/js/jquery.min.js
  static/cdnjs.cloudflare.com/js/leaflet.js
  static/cdnjs.cloudflare.com/webfonts/fa-brands-400.eot
  static/cdnjs.cloudflare.com/webfonts/fa-brands-400.svg
  static/cdnjs.cloudflare.com/webfonts/fa-brands-400.ttf
  static/cdnjs.cloudflare.com/webfonts/fa-brands-400.woff
  static/cdnjs.cloudflare.com/webfonts/fa-brands-400.woff2
  static/cdnjs.cloudflare.com/webfonts/fa-solid-900.eot
  static/cdnjs.cloudflare.com/webfonts/fa-solid-900.svg
  static/cdnjs.cloudflare.com/webfonts/fa-solid-900.ttf
  static/cdnjs.cloudflare.com/webfonts/fa-solid-900.woff
  static/cdnjs.cloudflare.com/webfonts/fa-solid-900.woff2
Labels: approved, lgtm, size/XXL

#79 [Fixes #78] Added the API to fetch latest version from the KubeEdge website.
  functions/latestversion.js
  netlify.toml
Labels: approved, lgtm, new-feature, size/S

#80 Added redirect in the URL to rewrite the path of latestversion API
  netlify.toml
Labels: approved, enhancement, lgtm, size/XS

#81 update latestversion to v1.4.0
  functions/latestversion.js
Labels: approved, lgtm, size/XS
