Repository kubeedge/website, pull requests merged in 2020-10, with the labels that each got.

#93 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS, spam

#96 website-v2: improve homepage content
  config/_default/languages.toml
  content/en/home/home_slider.md
  content/en/home/partners.md
  content/zh/home/home_slider.md
  content/zh/home/partners.md
  layouts/partials/widgets/slider.html
Labels: approved, lgtm, size/L

#97 Update README.md
  README.md
Labels: approved, lgtm, size/XS

#100 Redesign home
  content/en/blog/_index.md
  content/en/blog/cncf-sandbox-announcement/index.md
  content/en/blog/contributor-contest-announcement/index.md
  content/en/blog/contributor-contest/index.md
  content/en/blog/control-home-appliances-via-cloud/index.md
  content/en/blog/release-v0.2/index.md
  content/en/blog/release-v1.2/index.md
  content/en/blog/release-v1.3/index.md
  content/en/blog/secure-kubeedge/index.md
  content/en/home/home_slider.md
  content/zh/blog/cncf-sandbox-announcement/index.md
  content/zh/blog/contributor-contest-announcement/index.md
  content/zh/blog/contributor-contest/index.md
  content/zh/blog/kubeedge-deployment-manual/index.md
  content/zh/blog/release-v0.2/index.md
  content/zh/blog/release-v1.2/index.md
  content/zh/blog/release-v1.3/index.md
  content/zh/home/home_slider.md
  layouts/blog/list.html
  layouts/partials/css/academic.css
  layouts/partials/widgets/slider.html
  static/img/hero/content-background.png
  static/img/hero/content-kubeedge.png
Labels: approved, lgtm, size/L
