Repository kubeedge/website, pull requests merged in 2020-09, with the labels that each got.

#82 Translate documents in content/ko for v1.3 release
  content/ko/blog/_index.md
  content/ko/blog/release-v1.3/index.md
  content/ko/home/home_slider.md
Labels: approved, lgtm, size/L

#77 add version nav
  config/_default/config.toml
  layouts/partials/navbar.html
Labels: approved, lgtm, size/L

#83 hide Versions nav
  layouts/partials/navbar.html
Labels: approved, lgtm, size/S

#86 add Versions navbar
  config/_default/config.toml
  layouts/partials/navbar.html
Labels: approved, lgtm, size/L

#88 Add CNCF logo and trademark language to footer
  layouts/partials/footer_section.html
Labels: approved, lgtm, size/M

#89 Return Hugo code to the footer
  config/_default/config.toml
  layouts/partials/footer_section.html
Labels: lgtm, size/M

#90 Add v1.4 blog
  content/en/blog/release-v1.4/index.md
  content/en/home/home_slider.md
  content/zh/blog/release-v1.4/index.md
  content/zh/home/home_slider.md
Labels: approved, lgtm, size/L
