Repository kubeedge/website, pull requests merged in 2021-06, with the labels that each got.

#147 Fix: change remote URL
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#146 Update latest version to 1.6.2
  functions/latestversion.js
Labels: approved, lgtm, size/XS

#142 trans /content/zh/docs/advanced/cri.md
  content/zh/docs/advanced/cri_zh.md
Labels: approved, lgtm, size/L

#138 trans /content/docs/setup/keadm.md
  content/zh/docs/setup/keadm_zh.md
Labels: approved, lgtm, size/L

#141 trans /content/zh/docs/setup/config.md
  content/zh/docs/setup/config_zh.md
Labels: approved, lgtm, size/L

#149 add stalebot config
  .github/stale.yml
Labels: approved, lgtm, size/M

#150 Add cloudcore ha docs
  content/en/docs/setup/keadm.md
Labels: approved, lgtm, size/S

#152 Update latest version to v1.7.0
  functions/latestversion.js
Labels: approved, lgtm, size/XS

#153 Docs: commit command update
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#154 update versions branch
  config/_default/config.toml
Labels: approved, lgtm, size/S

#155 Update latest version to 1.7.1
  functions/latestversion.js
Labels: approved, lgtm, size/XS
