Repository kubeedge/website, pull requests merged in 2021-08, with the labels that each got.

#157 add blog for release v1.6
  content/en/blog/release-v1.6/index.md
Labels: approved, lgtm, size/L

#158 add blog for release v1.5
  content/en/blog/release-v1.5/index.md
Labels: approved, lgtm, size/M

#156 add blog for release-v1.7
  content/en/blog/release-v1.7/index.md
  content/en/home/home_slider.md
Labels: approved, lgtm, size/L

#159 fix some blog errors
  content/en/blog/release-v1.6/index.md
  content/en/blog/release-v1.7/index.md
Labels: approved, size/XS, lgtm

#161 Upgrade latest release to1.7.2
  functions/latestversion.js
Labels: size/XS

#162 update homepage
  assets/css/custom.css
  config/_default/menus.toml
  config/_default/params.toml
  content/en/author/admin/_index.md
  content/en/home/about.md
  content/en/home/hero.md
  content/en/home/home_slider.md
  content/en/home/posts.md
  content/en/home/required.md
  content/en/home/supporters.md
  content/en/home/talks.md
  content/en/home/why-kubeedge.md
  layouts/partials/widgets/supporters.html
  static/img/avatar.png
  static/img/kubeedge-horizontal-color.png
  static/img/kubeedge-icon-color.svg
  static/img/supporters/CAICT.jpg
  static/img/supporters/SEL-ZJU.svg
  static/img/supporters/arm.svg
  static/img/supporters/bocloud.svg
  static/img/supporters/buaa.png
  static/img/supporters/china-mobile.png
  static/img/supporters/china-mobile.svg
  static/img/supporters/china-telecom.svg
  static/img/supporters/china-unicom-wocloud.png
  static/img/supporters/click2cloud.svg
  static/img/supporters/daocloud.svg
  static/img/supporters/emq.svg
  static/img/supporters/futurewei-technologies.svg
  static/img/supporters/harmony-cloud.svg
  static/img/supporters/huawei.png
  static/img/supporters/inspur.svg
  static/img/supporters/jylink.png
  static/img/supporters/kubesphere.svg
  static/img/supporters/orange.png
  static/img/supporters/raisecom-technology.png
  static/img/supporters/samsung-electronics.svg
  static/img/supporters/szdgri.png
  static/img/supporters/tenxcloud.svg
  static/img/supporters/uestc.png
  static/img/supporters/ustc.svg
  static/img/supporters/xh-iot.svg
  static/img/supporters/zhejiang-lab.png
Labels: size/XL, approved, lgtm

#163 Updated the copyright year to 2021
  config/_default/config.toml
Labels: approved, size/XS, lgtm
