Repository kubeedge/website, pull requests merged in 2021-04, with the labels that each got.

#135 trans /content/zh/docs/roadmap.md
  content/en/docs/roadmap.md
  content/zh/docs/roadmap_zh.md
Labels: approved, lgtm, size/L

#139 trans /content/zh/docs/setup/local.md
  content/zh/docs/setup/local_zh.md
Labels: approved, lgtm, size/M

#140 trans /content/zh/docs/setup/upgrade.md
  content/zh/docs/setup/upgrade_zh.md
Labels: approved, lgtm, size/M

#143 Docs: add metamanager
  content/en/docs/architecture/edge/_index.md
Labels: approved, lgtm, size/XS
