Repository kubeedge/website, pull requests merged in 2021-03, with the labels that each got.

#128 Update latest version to v1.6.0
  functions/latestversion.js
Labels: approved, lgtm, size/XS

#129 refine router doc
  content/en/docs/developer/custom_message_deliver.md
Labels: approved, lgtm, size/M

#121 Docs: update debug.md
  content/en/docs/advanced/debug.md
Labels: approved, lgtm, size/L

#122 Docs: update metrics doc
  content/en/docs/advanced/metrics.md
Labels: approved, lgtm, size/M

#131 Dosc: trans README.md
  README_zh.md
Labels: approved, lgtm, size/M

#133 trans content/zh/docs/_index.md
  content/zh/docs/_index_zh.md
Labels: approved, lgtm, size/M

#134 trans /content/zh/docs/kubeedge.md
  content/zh/docs/kubeedge_zh.md
Labels: approved, lgtm, size/M

#137 Update the latest version to 1.6.1
  functions/latestversion.js
Labels: approved, lgtm, size/XS
