Repository kubeedge/website, pull requests merged in 2022-03, with the labels that each got.

#192 fix copyright date
  config/_default/config.toml
Labels: approved, size/XS, lgtm

#190 update keadm
  content/en/docs/setup/keadm.md
  content/zh/docs/setup/keadm_zh.md
Labels: approved, size/L, lgtm

#198 Accessibility add alt to image
  layouts/partials/footer_section.html
Labels: approved, size/XS, lgtm

#194 add the command to download keadm
  content/en/docs/setup/keadm.md
Labels: size/S, approved, lgtm

#195 update latest version to v1.10.0
  functions/latestversion.js
Labels: approved, size/XS, lgtm

#204 fix:markdown on various pages of doc
  content/en/docs/advanced/cri.md
  content/en/docs/advanced/edgemesh.md
  content/en/docs/architecture/edge/eventbus.md
  content/en/docs/developer/mappers/modbus.md
  content/en/docs/developer/message_topics.md
Labels: size/S, approved, lgtm

#196 keadm support beta join
  content/zh/docs/setup/keadm_zh.md
Labels: approved, size/L, lgtm

#202 Accessibility add link name
  layouts/partials/navbar.html
Labels: approved, size/XS, lgtm

#200 Accessibility update "go to top"
  layouts/partials/footer_section.html
Labels: approved, size/XS, lgtm

#203 fix:heading 3
  content/en/docs/setup/keadm.md
Labels: approved, size/XS, lgtm

#188 Improve code highlighting support
  config/_default/params.toml
Labels: approved, size/XS, lgtm

#206 fix Cloud Native logo on mobile & tablet
  layouts/partials/footer_section.html
Labels: approved, size/XS, lgtm

#208 Accessibility update social links
  themes/academic/layouts/partials/share.html
Labels: approved, size/XS, lgtm

#210 fix toggle menu on close
  themes/academic/layouts/partials/css/academic.css
Labels: size/S, approved, lgtm
