Repository kubeedge/website, pull requests merged in 2022-04, with the labels that each got.

#222 fix:broken link
  content/en/docs/developer/troubleshooting.md
Labels: approved, size/XS, lgtm

#220 update content links
  content/en/docs/advanced/edgemesh.md
  content/en/docs/developer/test/unit_test.md
  content/en/home/supporters.md
  content/en/slides/introducing-kubeedge.md
  content/ko/docs/getting-started-minikube.md
  content/ko/docs/getting-started.md
  content/ko/docs/unit-test-guide.md
  content/ko/slides/introducing-kubeedge.md
  content/zh/docs/advanced/edgemesh.md
  content/zh/docs/developer/test/unit_test.md
  content/zh/slides/introducing-kubeedge.md
Labels: approved, size/M, lgtm

#226 add redirect rule to edgemesh site
  netlify.toml
Labels: approved, size/XS, lgtm

#230 fix:incorrect numbering
  content/en/docs/developer/troubleshooting.md
Labels: approved, size/XS, lgtm

#229 fix:keadm setup page
  content/en/docs/setup/keadm.md
Labels: approved, size/M, lgtm

#228 fix:markdown
  content/en/docs/developer/mappers/bluetooth.md
Labels: size/S, approved, lgtm

#216 social icons ui update
  assets/css/custom.css
  layouts/partials/navbar.html
Labels: size/S, approved, lgtm

#227 update links
  layouts/_default/single.html
  layouts/talk/single.html
Labels: approved, size/XS, lgtm
