Repository kubeedge/website, pull requests merged in 2022-06, with the labels that each got.

#237 fix: doc style
  content/en/docs/developer/device_crd.md
Labels: approved, size/XS, lgtm

#236 Corrected grammar in the file
  content/en/author/admin/_index.md
Labels: size/S, approved, lgtm

#214 add & update favicons
  layouts/partials/favicons.html
  layouts/partials/header.html
  static/img/favicons/android-chrome-192x192.png
  static/img/favicons/android-chrome-384x384.png
  static/img/favicons/apple-touch-icon.png
  static/img/favicons/browserconfig.xml
  static/img/favicons/favicon-16x16.png
  static/img/favicons/favicon-32x32.png
  static/img/favicons/favicon.ico
  static/img/favicons/mstile-150x150.png
  static/img/favicons/site.webmanifest
Labels: approved, size/L, lgtm

#238 fix:shell command
  content/en/docs/setup/config.md
Labels: approved, size/XS, lgtm

#234 add: support for json highlighting
  config/_default/params.toml
  content/en/docs/setup/config.md
Labels: approved, size/XS, lgtm

#240 fix scalability test report blog index
  content/zh/blog/scalability-test-report/images/connect-number.png
  content/zh/blog/scalability-test-report/images/deploy.png
  content/zh/blog/scalability-test-report/images/edgemark-deploy.png
  content/zh/blog/scalability-test-report/images/k8s-scalability.png
  content/zh/blog/scalability-test-report/images/kube-apiserver-usage.png
  content/zh/blog/scalability-test-report/images/kubeedge-arch.png
  content/zh/blog/scalability-test-report/images/kubeedge-kube-apiserver-usage.png
  content/zh/blog/scalability-test-report/images/mutating-api-latency.png
  content/zh/blog/scalability-test-report/images/network.png
  content/zh/blog/scalability-test-report/images/read-only-api-call-cluster.png
  content/zh/blog/scalability-test-report/images/read-only-api-call-namespace.png
  content/zh/blog/scalability-test-report/images/read-only-api-call-resource.png
  content/zh/blog/scalability-test-report/index.md
Labels: size/XL, approved, lgtm

#235 update doc of keadm page
  content/en/docs/setup/keadm.md
Labels: size/S, approved, lgtm

#243 updated ha.md
  content/en/docs/setup/ha.md
Labels: approved, size/L, lgtm

#244 updated kubeedge components
  content/en/docs/kubeedge.md
Labels: approved, size/XS, lgtm

#241 added serviceBus doc
  content/en/docs/architecture/edge/servicebus.md
  static/img/servicebus/servicebus-flowchart.png
Labels: size/S, approved, lgtm

#242 update mapper doc
  content/en/docs/developer/mappers/_index.md
Labels: size/S, approved, lgtm

#247 update hugo
  netlify.toml
Labels: approved, size/XS, lgtm

#248 Add Ci4Rail to supporters
  content/en/home/supporters.md
  static/img/supporters/ci4rail.png
Labels: approved, size/XS, lgtm

#249 fix typo
  content/en/docs/advanced/debug.md
Labels: approved, size/XS, lgtm
