Repository kubeedge/website, pull requests merged in 2022-09, with the labels that each got.

#257 add svg favicon
  layouts/partials/favicons.html
  static/img/favicons/favicon.png
  static/img/favicons/favicon.svg
Labels: approved, size/XS, lgtm

#255 fix Pod Startup Latency slo
  content/zh/blog/scalability-test-report/index.md
Labels: approved, size/XS, lgtm

#258 update keadm doc
  content/en/docs/setup/keadm.md
  content/zh/docs/setup/keadm.md
  content/zh/docs/setup/keadm_zh.md
Labels: size/S, approved, lgtm

#259 add vastaitech to supporters
  content/en/home/supporters.md
  static/img/supporters/vastaitech.svg
Labels: approved, size/XS, lgtm

#251 Add subproject(Sedna,Ianvs) entry to documents on kubeedge.io
  config/_default/menus.toml
  content/en/docs/subproject/ianvs.md
  content/en/docs/subproject/sedna.md
  static/img/subproject/ianvs_arch.png
  static/img/subproject/sedna_arch.png
Labels: approved, size/L, lgtm
