Repository kubeedge/website, pull requests merged in 2022-12, with the labels that each got.

#274 [Course Task] bugfix/doc
  content/en/docs/advanced/debug.md
Labels: approved, size/XS, lgtm

#270 update edgemesh integration doc
  content/en/docs/advanced/edgemesh.md
  content/zh/docs/advanced/edgemesh.md
Labels: approved, size/L, lgtm

#278 [Course Task] fix-doc-edge-controller
  content/en/docs/architecture/cloud/edge_controller.md
Labels: approved, size/M, lgtm

#279 update installation docs
  content/en/docs/setup/keadm.md
  content/en/docs/setup/local.md
Labels: approved, size/L, lgtm

#285 [Course Task] doc-eventbus
  content/en/docs/architecture/edge/eventbus.md
Labels: approved, size/XS, lgtm

#276 [Course Task] bugfix/content/en/docs/architecture/edge/cloudhub
  content/en/docs/architecture/cloud/cloudhub.md
Labels: size/S, approved, lgtm

#280 [Course Task] Doc devicetwin
  content/en/docs/architecture/edge/devicetwin.md
Labels: approved, size/L, lgtm

#283 [Course Task] doc-metaserver
  content/en/docs/architecture/edge/metamanager.md
Labels: size/S, approved, lgtm

#284 [Course Task] doc-servicebus
  content/en/docs/architecture/edge/servicebus.md
Labels: approved, size/XS, lgtm
