Repository kubeedge/website, pull requests merged in 2023-08, with the labels that each got.

#365 Fix broken link of text security team
  blog/security-threat-model/index.md
Labels: size/S, approved, lgtm

#369 SLSA-GitHub-generator wrong link fix
  i18n/zh/docusaurus-plugin-content-blog/reach-slsa-l3/index.md
Labels: size/XS

#375 Update links in supporters section
  src/components/supporters/index.js
Labels: approved, size/XS, lgtm

#380 Remove outdated description for old version
  content/en/docs/setup/keadm.md
Labels: approved, size/XS, lgtm

#395 responsiveness of the Why KubeEdge section
  src/components/why/styles.module.css
Labels: size/S, approved, lgtm

#400 changed the roadmap and setup links
  blog/cncf-sandbox-announcement/index.mdx
  i18n/zh/docusaurus-plugin-content-blog/cncf-sandbox-announcement/index.mdx
Labels: approved, size/XS, lgtm

#384 Fixed Slider Section responsiveness
  src/components/slider/index.js
  src/components/slider/index.scss
Labels: size/S, approved, lgtm

#343 ADD: Add catalog translation.
  i18n/zh/docusaurus-plugin-content-docs/current.json
  i18n/zh/docusaurus-plugin-content-docs/current/architecture/beehive.md
  i18n/zh/docusaurus-plugin-content-docs/current/home.md
  i18n/zh/docusaurus-plugin-content-docs/current/roadmap.md
  i18n/zh/docusaurus-plugin-content-docs/current/setup/ha.md
Labels: size/S, approved, lgtm

#346 update and add favicons
  docusaurus.config.js
  static/favicons/android-chrome-192x192.png
  static/favicons/android-chrome-384x384.png
  static/favicons/apple-touch-icon.png
  static/favicons/browserconfig.xml
  static/favicons/favicon-16x16.png
  static/favicons/favicon-32x32.png
  static/favicons/favicon.ico
  static/favicons/mstile-150x150.png
  static/favicons/site.webmanifest
  static/img/favicon.ico
Labels: approved, size/M, lgtm

#354 [Bug] - Fixed Unrendered Escape Characters
  i18n/zh/code.json
  src/components/why/index.js
Labels: approved, size/M, lgtm

#357 [Bug] - Fixed Ordering of List Numbers
  CONTRIBUTING.md
  README.md
  README_zh.md
  blog/release-v1.2/index.mdx
  docs/advanced/cri.md
  docs/developer/device_crd.md
  docs/setup/keadm.md
  docs/subproject/ianvs.md
  i18n/zh/docusaurus-plugin-content-blog/release-v1.2/index.mdx
  i18n/zh/docusaurus-plugin-content-docs/current/developer/device_crd.md
  i18n/zh/docusaurus-plugin-content-docs/current/setup/keadm.md
  i18n/zh/docusaurus-plugin-content-docs/current/subproject/ianvs.md
Labels: approved, size/L, lgtm

#378 Mobile view fix
  src/components/blogPost/index.scss
Labels: approved, size/XS, lgtm

#402 eliminate space in logo title
  i18n/zh/docusaurus-theme-classic/navbar.json
Labels: approved, size/XS, lgtm

#403 fixed duplicacy in unit_test docs
  docs/developer/test/unit_test.md
Labels: approved, size/XS, lgtm

#406 Update multi versions for docs
  docusaurus.config.js
  versionsArchived.json
Labels: approved, size/M, lgtm

#407 update multi versions for docs
  docusaurus.config.js
  versionsArchived.json
Labels: approved, size/M, lgtm

#408 update multi versions for docs
  docusaurus.config.js
  versionsArchived.json
Labels: approved, size/M, lgtm

#409 update version for release-1.12
  config/_default/config.toml
  config/_default/menus.toml
  layouts/partials/navbar.html
Labels: approved, size/M, lgtm

#410 Support multi-versions for docs
  config/_default/config.toml
  config/_default/menus.toml
  layouts/partials/navbar.html
Labels: approved, size/M, lgtm

#404 add job center
  docusaurus.config.js
  i18n/zh/code.json
  i18n/zh/docusaurus-plugin-content-page/job-center/demo/index.mdx
  i18n/zh/docusaurus-theme-classic/navbar.json
  package.json
  src/components/icons/index.js
  src/components/jobCard/README.md
  src/components/jobCard/index.js
  src/components/jobCard/styles.scss
  src/pages/job-center/demo/index.mdx
  src/pages/job-center/index.js
  src/pages/job-center/index.scss
  src/plugins/jobCenterGlobalData/index.js
  static/img/icon/company.svg
  static/img/icon/location.svg
  static/img/jobcenter/header.jpg
  yarn.lock
Labels: size/XXL, approved, lgtm

#382 update dependency
  package.json
  yarn.lock
Labels: approved, size/M, lgtm

#414 [feat]:Added hover effect to Supporters Cards
  src/components/supporters/index.js
  src/components/supporters/index.scss
Labels: approved, size/M, lgtm

#417 switch code CODE_OF_CONDUCT to CNCF COC
  CODE_OF_CONDUCT.md
Labels: approved, size/M, lgtm

#416 Add URL for Supporters section in home page
  docusaurus.config.js
  src/pages/index.js
Labels: size/S, approved, lgtm

#420 add supporter info of orientsky
  src/components/supporters/index.js
  static/img/supporters/orientsky.jpg
Labels: approved, size/XS, lgtm
