Repository kubeedge/website, pull requests merged in 2023-11, with the labels that each got.

#442 add case studies instruction
  docs/community/casestudies.md
  i18n/zh/docusaurus-plugin-content-docs/current/community/casestudies.md
Labels: approved, size/M, lgtm

#446 Support docs for v1.15
  versionsArchived.json
Labels: approved, size/XS, lgtm

#449 Support docs v1.15 jump in release1.14
  versionsArchived.json
Labels: approved, size/XS, lgtm

#448 Support v1.15 jump in release 1.13
  versionsArchived.json
Labels: approved, size/XS, lgtm

#450 support docs for v1.15 in release-1.12
  config/_default/config.toml
Labels: size/S, approved, lgtm

#451 add docs Next version
  versionsArchived.json
Labels: approved, size/XS, lgtm

#454 add Next version in v1.14 doc
  versionsArchived.json
Labels: approved, size/XS, lgtm

#455 add Next version in v1.12 doc
  config/_default/config.toml
Labels: approved, size/XS, lgtm

#453 add Next version in v1.13 doc
  versionsArchived.json
Labels: approved, size/XS, lgtm

#452 add Next version in release-1.15
  versionsArchived.json
Labels: approved, size/XS, lgtm

#432 Sync some adopters from kubeedge/kubeedge to supporters
  src/components/supporters/index.js
  static/img/supporters/pits-logo.svg
  static/img/supporters/twowin-logo.png
Labels: approved, size/M, lgtm

#441 add case studies
  docusaurus.config.js
  i18n/zh/code.json
  i18n/zh/docusaurus-plugin-content-page/case-studies/caseDemo1/index.mdx
  i18n/zh/docusaurus-plugin-content-page/case-studies/caseDemo2/index.mdx
  i18n/zh/docusaurus-theme-classic/navbar.json
  src/components/caseCard/index.js
  src/components/caseCard/styles.scss
  src/components/tagToggle/index.js
  src/components/tagToggle/index.scss
  src/const/index.js
  src/pages/case-studies/caseDemo1/index.mdx
  src/pages/case-studies/caseDemo2/index.mdx
  src/pages/case-studies/index.js
  src/pages/case-studies/index.scss
  src/plugins/caseStudiesGlobalData/index.js
  static/img/casestudies/case1.jpg
  static/img/casestudies/case2.jpg
  static/img/casestudies/case3.jpg
  static/img/casestudies/case4.jpg
  static/img/casestudies/case5.jpg
  static/img/casestudies/case6.jpg
  static/img/casestudies/header.jpg
Labels: size/XL, approved, lgtm

#458 fix i18n pages directory name and case description
  docusaurus.config.js
  i18n/zh/docusaurus-plugin-content-pages/case-studies/caseDemo1/index.mdx
  i18n/zh/docusaurus-plugin-content-pages/case-studies/caseDemo2/index.mdx
  i18n/zh/docusaurus-plugin-content-pages/job-center/demo/index.mdx
  src/components/caseCard/styles.scss
  src/plugins/caseStudiesGlobalData/index.js
  src/plugins/jobCenterGlobalData/index.js
Labels: size/S, approved, lgtm

#459 support casecard background elastic adaptation
  src/components/caseCard/styles.scss
Labels: approved, size/XS, lgtm

#460 Update case study for solutions
  i18n/zh/code.json
  src/pages/case-studies/index.js
Labels: approved, size/XS, lgtm

#457 add use case for china's highways and cnooc
  src/pages/case-studies/caseDemo1/index.mdx
  src/pages/case-studies/caseDemo2/index.mdx
  src/pages/case-studies/chinahighways/images/edgemesh-statefulsets.png
  src/pages/case-studies/chinahighways/images/electronic-toll-booths.png
  src/pages/case-studies/chinahighways/images/kubeedge-edge-nodes-cloud.png
  src/pages/case-studies/chinahighways/index.mdx
  src/pages/case-studies/cnooc/index.mdx
Labels: approved, size/L, lgtm

#464 optimize hover effect to Supporters Cards
  src/components/supporters/index.scss
Labels: approved, size/XS, lgtm
