Repository kubeedge/website, pull requests merged in 2023-12, with the labels that each got.

#468 Add decice as supporter
  src/components/supporters/index.js
  static/img/supporters/decice.svg
Labels: approved, size/M, lgtm

#469 Add oehi to supporter
  src/components/supporters/index.js
  static/img/supporters/oehi.svg
Labels: size/S, approved, lgtm

#465 Update kubeedge slack invitation link to cncf
  docs/community/slack.md
  docusaurus.config.js
Labels: size/S, approved, lgtm

#477 fix slack url
  blog/cncf-sandbox-announcement/index.mdx
  blog/contributor-contest/index.mdx
  docs/welcome/getting-started.md
  i18n/zh/docusaurus-plugin-content-blog/cncf-sandbox-announcement/index.mdx
  i18n/zh/docusaurus-plugin-content-blog/contributor-contest/index.mdx
  i18n/zh/docusaurus-plugin-content-docs/current/welcome/getting-started.md
Labels: size/S, approved, lgtm

#480 update latestversion v1.15.1
  functions/latestversion.js
Labels: approved, size/XS, lgtm

#479 add supporters instructions
  docs/community/supporters.md
  i18n/zh/docusaurus-plugin-content-docs/current/community/supporters.md
Labels: approved, size/M, lgtm

#488 Update kubernetes.md
  docs/setup/prerequisites/kubernetes.md
Labels: approved, size/XS, lgtm

#482 add link at Supporters redirect to the instructions doc.
  docs/community/supporters.md
  i18n/zh/code.json
  i18n/zh/docusaurus-plugin-content-docs/current/community/supporters.md
  i18n/zh/docusaurus-theme-classic/navbar.json
  src/components/supporters/index.js
  src/components/supporters/index.scss
Labels: approved, size/M, lgtm

#478 add some runtime related faq
  docs/faq/setup.md
  i18n/zh/docusaurus-plugin-content-docs/current/faq/setup.md
Labels: approved, size/L, lgtm

#490 Add Partners page
  docs/community/partners.md
  docusaurus.config.js
  i18n/zh/code.json
  i18n/zh/docusaurus-plugin-content-docs/current/community/partners.md
  i18n/zh/docusaurus-theme-classic/navbar.json
  src/pages/partners/index.js
  src/pages/partners/index.scss
  src/pages/partners/partners.mdx
  static/img/partners.jpg
Labels: approved, size/L, lgtm

#491 Add DaoCloud as A KubeEdge Partner
  src/pages/partners/partners.mdx
Labels: approved, size/XS, lgtm

#492 Add sf tech to community
  src/components/supporters/index.js
  static/img/supporters/sf-tech.png
Labels: approved, size/XS, lgtm

#466 Add Case for CMCC panzhou panji platform
  i18n/zh/docusaurus-plugin-content-pages/case-studies/CMCC/index.mdx
  src/pages/case-studies/CMCC/index.mdx
  static/img/casestudies/CMCC/cmcc_kubeedge_arch.png
  static/img/casestudies/CMCC/panji_platform.png
  static/img/casestudies/CMCC/platform.png
Labels: approved, size/M, lgtm

#494 Fix enduser to usercase
  docs/community/casestudies.md
  i18n/zh/docusaurus-plugin-content-docs/current/community/casestudies.md
  src/const/index.js
  src/pages/case-studies/chinahighways/index.mdx
  src/pages/case-studies/cnooc/index.mdx
Labels: size/S, approved, lgtm

#495 rename enduser to usercase tag in CMCC case
  i18n/zh/docusaurus-plugin-content-pages/case-studies/CMCC/index.mdx
  i18n/zh/docusaurus-plugin-content-pages/case-studies/caseDemo1/index.mdx
  i18n/zh/docusaurus-plugin-content-pages/case-studies/caseDemo2/index.mdx
  src/pages/case-studies/CMCC/index.mdx
Labels: approved, size/M, lgtm

#498 add case study for ctyun
  i18n/zh/docusaurus-plugin-content-pages/case-studies/ctyun/index.mdx
  src/pages/case-studies/ctyun/index.mdx
  static/img/casestudies/ctyun/backgroud.png
  static/img/casestudies/ctyun/connectionChanges.png
  static/img/casestudies/ctyun/equilibriumSituation.png
  static/img/casestudies/ctyun/fileDistribution.png
  static/img/casestudies/ctyun/managementPlan.png
  static/img/casestudies/ctyun/nodeArchitecture.png
  static/img/casestudies/ctyun/overallProcess.png
  static/img/casestudies/ctyun/recoveryMigration.png
  static/img/casestudies/ctyun/serviceContainer.png
  static/img/casestudies/ctyun/unbalancedConnection.png
  static/img/casestudies/ctyun/upgradePlan.png
Labels: approved, size/L, lgtm

#496 Add Chinese version of china highways etc usercase
  i18n/zh/docusaurus-plugin-content-pages/case-studies/chinahighways/images/batch-job.png
  i18n/zh/docusaurus-plugin-content-pages/case-studies/chinahighways/images/edgemesh-statefulsets.png
  i18n/zh/docusaurus-plugin-content-pages/case-studies/chinahighways/images/kubeedge-edge-nodes-cloud.png
  i18n/zh/docusaurus-plugin-content-pages/case-studies/chinahighways/index.mdx
Labels: approved, size/M, lgtm

#497 Add user case for Satellite
  i18n/zh/docusaurus-plugin-content-pages/case-studies/satellite/images/satellite.png
  i18n/zh/docusaurus-plugin-content-pages/case-studies/satellite/index.mdx
  src/pages/case-studies/satellite/index.mdx
Labels: approved, size/M, lgtm

#499 add case study for zcitc
  i18n/zh/docusaurus-plugin-content-pages/case-studies/zcitc/index.mdx
  src/pages/case-studies/zcitc/index.mdx
  static/img/casestudies/zcitc/EdgeArchitecture.png
  static/img/casestudies/zcitc/KubernetesCluster.png
  static/img/casestudies/zcitc/MasterSlave.png
  static/img/casestudies/zcitc/kubeedgeArchitecture.png
  static/img/casestudies/zcitc/systemStructure.png
Labels: approved, size/M, lgtm

#502 add sf tech user case
  i18n/zh/docusaurus-plugin-content-pages/case-studies/SF-Tech/index.mdx
  src/pages/case-studies/SF-Tech/index.mdx
  static/img/casestudies/sf-tech/IIOT-arch.png
  static/img/casestudies/sf-tech/IIOT-system.png
  static/img/casestudies/sf-tech/OT-IT.png
  static/img/casestudies/sf-tech/edgecomputing-OT.png
  static/img/casestudies/sf-tech/kubeedge-arch.png
Labels: approved, size/M, lgtm

#501 add caii case
  i18n/zh/docusaurus-plugin-content-pages/case-studies/CAII/index.mdx
  src/pages/case-studies/CAII/index.mdx
  static/img/casestudies/CAII/arch.png
  static/img/casestudies/CAII/background.png
  static/img/casestudies/CAII/data-process.png
Labels: approved, size/L, lgtm
