Repository kubeedge/website, pull requests merged in 2023-01, with the labels that each got.

#277 [Course Task] fix-doc-device-controller
  content/en/docs/architecture/cloud/device_controller.md
Labels: approved, size/M, lgtm

#282 fix some errors of the document
  content/en/docs/architecture/cloud/edge_controller.md
  content/en/docs/architecture/edge/edged.md
  content/en/docs/community/contribute.md
  content/en/docs/developer/device_crd.md
  content/en/docs/developer/mappers/modbus.md
  content/en/docs/developer/test/unit_test.md
  content/en/docs/developer/troubleshooting.md
  content/en/docs/setup/config.md
  content/en/docs/setup/keadm.md
  content/zh/docs/architecture/edge/edged.md
  content/zh/docs/community/contribute.md
  content/zh/docs/developer/device_crd.md
  content/zh/docs/developer/mappers/modbus.md
  content/zh/docs/developer/test/unit_test.md
  content/zh/docs/developer/troubleshooting.md
  content/zh/docs/setup/config.md
  content/zh/docs/setup/keadm.md
Labels: approved, size/M, lgtm

#287 [Course Task] doc-bluetooth
  content/zh/docs/developer/mappers/bluetooth.md
Labels: approved, size/XS, lgtm

#286 [Course Task] doc-device-crd
  content/en/docs/developer/device_crd.md
Labels: approved, size/M, lgtm, do-not-merge/hold

#268 min img folder svg
  static/img/kubeedge-200.svg
  static/img/kubeedge-icon-color.svg
Labels: size/S, approved, lgtm

#266 min supporters folder svg
  static/img/supporters/SEL-ZJU.svg
  static/img/supporters/arm.svg
  static/img/supporters/bocloud.svg
  static/img/supporters/china-mobile.svg
  static/img/supporters/china-telecom.svg
  static/img/supporters/click2cloud.svg
  static/img/supporters/daocloud.svg
  static/img/supporters/emq.svg
  static/img/supporters/futurewei-technologies.svg
  static/img/supporters/harmony-cloud.svg
  static/img/supporters/ictnj.svg
  static/img/supporters/inspur.svg
  static/img/supporters/kubesphere.svg
  static/img/supporters/samsung-electronics.svg
  static/img/supporters/tenxcloud.svg
  static/img/supporters/ustc.svg
  static/img/supporters/vastaitech.svg
  static/img/supporters/xh-iot.svg
Labels: size/XXL, approved, lgtm

#289 update url of installation-package
  content/en/docs/setup/keadm.md
Labels: approved, size/XS, lgtm

#261 fix format about avoiding kube-proxy being deployed on edgenode
  content/en/docs/setup/keadm.md
Labels: size/S, approved, lgtm

#272 add installation debug docs
  content/en/docs/setup/debug.md
Labels: approved, size/L, lgtm
