Repository kubeedge/website, pull requests merged in 2023-07, with the labels that each got.

#327 add supporter info of njhyst
  content/en/home/supporters.md
  static/img/supporters/njhyst.png
Labels: approved, size/XS, lgtm

#334 remove expired sliders.
  src/components/slider/index.js
Labels: size/S, approved, lgtm

#331 Upgrade to Google Analytics GA4
  docusaurus.config.js
Labels: size/S, approved, lgtm

#340 remove package-lock.json
  package-lock.json
Labels: size/XXL, approved, lgtm

#337 add Shelley-BaoYue as reviewer and approver
  OWNERS
Labels: approved, size/XS, lgtm

#344 update blog posts, limit abstract length in blog post list
  blog/cncf-sandbox-announcement/index.mdx
  blog/contributor-contest-announcement/index.mdx
  blog/contributor-contest/index.mdx
  blog/control-home-appliances-via-cloud/index.mdx
  blog/reach-slsa-l3/index.md
  blog/release-v0.2/index.mdx
  blog/release-v1.2/index.mdx
  blog/release-v1.3/index.mdx
  blog/release-v1.4/index.mdx
  blog/release-v1.5/index.mdx
  blog/release-v1.6/index.mdx
  blog/release-v1.7/index.mdx
  blog/release-v1.8/index.mdx
  blog/release-v1.9/index.mdx
  blog/scalability-test-report/index.md
  blog/secure-kubeedge/index.md
  blog/security-threat-model/index.md
Labels: approved, size/M, lgtm

#336 update dependency
  package.json
  yarn.lock
Labels: approved, size/L, lgtm

#359 [Bug] - Fixed Edit this Page Links
  docusaurus.config.js
Labels: approved, size/XS, lgtm
