Repository kubeedge/website, pull requests merged in 2024-08, with the labels that each got.

#591 Add Supplemental Developer Contribution Guidelines
  CONTRIBUTING.md
  docs/developer/Supplemental_developer_guide.md
Labels: approved, size/M, lgtm

#608 fix: changed crd path
  docs/setup/install-with-binary.md
Labels: approved, size/XS, lgtm

#612 Update the kubernetes compatibility-v1.16
  docs/setup/prerequisites/kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/current/setup/prerequisites/kubernetes.md
Labels: approved, size/M, lgtm

#611 Update the kubernetes compatibility-v1.17
  docs/setup/prerequisites/kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/current/setup/prerequisites/kubernetes.md
Labels: approved, size/M, lgtm

#630 fix: fixed register node step
  docs/setup/config.md
  i18n/zh/docusaurus-plugin-content-docs/current/setup/config.md
Labels: size/S, approved, lgtm

#596 Update year to 2024 in Chinese page
  i18n/zh/docusaurus-theme-classic/footer.json
Labels: approved, size/XS, lgtm

#623 Update versions for 1.18
  versionsArchived.json
Labels: approved, size/XS, lgtm
