Repository kubeedge/website, pull requests merged in 2024-01, with the labels that each got.

#504 change caii tag to usercase
  i18n/zh/docusaurus-plugin-content-pages/case-studies/CAII/index.mdx
  src/pages/case-studies/CAII/index.mdx
Labels: approved, size/XS, lgtm

#505 Standardize Partners sort
  docs/community/partners.md
  i18n/zh/docusaurus-plugin-content-docs/current/community/partners.md
  src/pages/partners/partners.mdx
Labels: approved, size/XS, lgtm

#503 add case customer service cloud-edge collaboration platform
  i18n/zh/docusaurus-plugin-content-pages/case-studies/CMCC-10086/index.mdx
  src/pages/case-studies/CMCC-10086/index.mdx
  static/img/casestudies/CMCC-10086/cloud-native-route.png
  static/img/casestudies/CMCC-10086/edge-cluster-or-node.png
  static/img/casestudies/CMCC-10086/edge-network.png
  static/img/casestudies/CMCC-10086/edge-proxy.png
  static/img/casestudies/CMCC-10086/edge-resource-management.png
  static/img/casestudies/CMCC-10086/fault-isolation.png
  static/img/casestudies/CMCC-10086/image-registry.png
  static/img/casestudies/CMCC-10086/k8s-kubeedge-kubevirt.png
  static/img/casestudies/CMCC-10086/middleware.png
  static/img/casestudies/CMCC-10086/monitor.png
  static/img/casestudies/CMCC-10086/nationwide-deployment.png
  static/img/casestudies/CMCC-10086/network.png
  static/img/casestudies/CMCC-10086/offline-ip-retention.png
  static/img/casestudies/CMCC-10086/roadmap.png
  static/img/casestudies/CMCC-10086/service-discovery.png
  static/img/casestudies/CMCC-10086/traffic-topology.png
Labels: approved, size/L, lgtm

#500 user case kuiper
  i18n/zh/docusaurus-plugin-content-pages/case-studies/Kuiper/index.mdx
  src/pages/case-studies/Kuiper/index.mdx
  static/img/casestudies/kuiper/android_plugin.png
  static/img/casestudies/kuiper/aws.png
  static/img/casestudies/kuiper/big_data_center.png
  static/img/casestudies/kuiper/configuration.png
  static/img/casestudies/kuiper/demo_stream.png
  static/img/casestudies/kuiper/edgex_foundry.png
  static/img/casestudies/kuiper/edgex_foundry2.png
  static/img/casestudies/kuiper/kubeedge&kuiper.png
  static/img/casestudies/kuiper/kuiper_architecture.png
  static/img/casestudies/kuiper/multiple_nodes.png
  static/img/casestudies/kuiper/rules.png
  static/img/casestudies/kuiper/stream.png
  static/img/casestudies/kuiper/target_attribute.png
  static/img/casestudies/kuiper/write_rules.png
Labels: approved, size/L, lgtm

#513 Fix tag from solutions to solution
  docs/community/casestudies.md
  i18n/zh/docusaurus-plugin-content-docs/current/community/casestudies.md
  src/const/index.js
Labels: approved, size/XS, lgtm

#512 add kubesphere to the partner
  src/pages/partners/partners.mdx
Labels: approved, size/XS, lgtm

#517 New Blog for Release 1.16
  blog/authors.yml
  blog/release-v1.16/index.mdx
  i18n/zh/docusaurus-plugin-content-blog/authors.yml
  i18n/zh/docusaurus-plugin-content-blog/release-v1.16/index.mdx
Labels: size/XL, approved, lgtm

#474 update container runtime docs
  docs/setup/prerequisites/runtime.md
  i18n/zh/docusaurus-plugin-content-docs/current/setup/prerequisites/runtime.md
Labels: approved, size/L, lgtm
