Repository kubeedge/website, pull requests merged in 2024-05, with the labels that each got.

#530 remove some `tbd` docs temporarily
  docs/advanced/application.md
  docs/concept/device/_category_.json
  docs/concept/device/dmi.md
  docs/concept/device/mapper.md
  docs/concept/edgemesh.md
  docs/setup/install-offline.md
  docs/setup/install-tools/_category_.json
  docs/setup/install-tools/keadm.md
  docs/setup/install-tools/keink.md
  docs/setup/prerequisites/OSandResources.md
  docs/welcome/available-doc-versions.md
  i18n/zh/docusaurus-plugin-content-docs/current/advanced/application.md
  i18n/zh/docusaurus-plugin-content-docs/current/concept/device/_category_.json
  i18n/zh/docusaurus-plugin-content-docs/current/concept/device/dmi.md
  i18n/zh/docusaurus-plugin-content-docs/current/concept/device/mapper.md
  i18n/zh/docusaurus-plugin-content-docs/current/concept/edgemesh.md
  i18n/zh/docusaurus-plugin-content-docs/current/setup/install-offline.md
  i18n/zh/docusaurus-plugin-content-docs/current/setup/install-tools/_category_.json
  i18n/zh/docusaurus-plugin-content-docs/current/setup/install-tools/keadm.md
  i18n/zh/docusaurus-plugin-content-docs/current/setup/install-tools/keink.md
  i18n/zh/docusaurus-plugin-content-docs/current/setup/prerequisites/OSandResources.md
  i18n/zh/docusaurus-plugin-content-docs/current/setup/prerequisites/kubernetes.md
  i18n/zh/docusaurus-plugin-content-docs/current/welcome/available-doc-versions.md
Labels: approved, size/L, lgtm

#481 fix zh docs
  i18n/zh/code.json
Labels: approved, size/M, lgtm

#439 Add device crd, mapper, mapper-framework docs
  docs/concept/device/device_crds.md
  docs/concept/device/mapper.md
  docs/developer/device_crd.md
  docs/developer/dmi.md
  docs/developer/mapper-framework.md
  docs/developer/mappers/bluetooth.md
  docs/developer/mappers/index.md
  docs/developer/mappers/modbus.md
  i18n/zh/docusaurus-plugin-content-docs/current/concept/device/device_crds.md
  i18n/zh/docusaurus-plugin-content-docs/current/concept/device/mapper.md
  i18n/zh/docusaurus-plugin-content-docs/current/developer/device_crd.md
  i18n/zh/docusaurus-plugin-content-docs/current/developer/dmi.md
  i18n/zh/docusaurus-plugin-content-docs/current/developer/mapper-framework.md
  i18n/zh/docusaurus-plugin-content-docs/current/developer/mappers/bluetooth.md
  i18n/zh/docusaurus-plugin-content-docs/current/developer/mappers/index.md
  i18n/zh/docusaurus-plugin-content-docs/current/developer/mappers/modbus.md
  static/img/device/DMI.png
  static/img/device/dmi-datapanel.png
  static/img/device/mapper-framework.png
  static/img/device/mapper.png
Labels: size/XXL, approved, lgtm

#529 New blog for summer-ospp
  blog/summer-ospp/index.md
  i18n/zh/docusaurus-plugin-content-blog/summer-ospp/images/summer-01.png
  i18n/zh/docusaurus-plugin-content-blog/summer-ospp/images/summer-02.png
  i18n/zh/docusaurus-plugin-content-blog/summer-ospp/index.md
Labels: approved, size/L, lgtm

#537 PR template goes inside `.github`
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/XS, lgtm

#539 New Blog for Release KubeEdge v1.12
  blog/release-v1.12/index.mdx
Labels: approved, size/M, lgtm

#534 New Blog for Release KubeEdge v1.17
  blog/release-v1.17/index.mdx
Labels: approved, size/L, lgtm

#535 New Blog for Release KubeEdge v1.10
  blog/release-v1.10/index.mdx
Labels: approved, size/L, lgtm

#538 New Blog for Release KubeEdge v1.11
  blog/release-v1.11/index.mdx
Labels: approved, size/L, lgtm

#542 New Blog for Release KubeEdge v1.13
  blog/release-v1.13/index.mdx
Labels: approved, size/L, lgtm

#541 New Blog for Release KubeEdge v1.14
  blog/release-v1.14/index.mdx
Labels: approved, size/M, lgtm

#545 Update doc version for 1.17
  versionsArchived.json
Labels: approved, size/XS, lgtm

#546 Update docs version for release 1.17
  versionsArchived.json
Labels: approved, size/XS, lgtm

#547 Update docs version for release 1.17
  versionsArchived.json
Labels: approved, size/XS, lgtm

#548 Update version for release 1.17
  versionsArchived.json
Labels: approved, size/XS, lgtm

#549 Update version for release 1.17
  versionsArchived.json
Labels: approved, size/XS, lgtm

#543 Replacing Twitter with X
  docusaurus.config.js
  src/css/custom.css
  static/img/twitter.svg
  static/img/x.svg
Labels: size/S, approved, lgtm

#555 Add case study about Raisecom Tech
  i18n/zh/docusaurus-plugin-content-pages/case-studies/Raisecom-Tech/index.mdx
  src/pages/case-studies/Raisecom-Tech/index.mdx
Labels: approved, size/M, lgtm

#556 Add case study about XingHai IoT
  i18n/zh/docusaurus-plugin-content-pages/case-studies/XingHai/index.mdx
  src/pages/case-studies/XingHai/index.mdx
Labels: approved, size/M, lgtm
