Repository kubeedge/website, pull requests merged in 2024-06, with the labels that each got.

#544 Docs: Improving the install with `keadm` documentation
  docs/setup/install-with-keadm.md
Labels: approved, size/L, lgtm

#569 Add LookCan to community
  src/components/supporters/index.js
  static/img/supporters/lookcan-logo.svg
Labels: size/S, approved, lgtm

#557 Add case study about JingYing Shuzhi Technology
  i18n/zh/docusaurus-plugin-content-pages/case-studies/jingying/index.mdx
  src/pages/case-studies/jingying/index.mdx
Labels: approved, size/M, lgtm

#567 Bug: We need to fix some links for local development
  docusaurus.config.js
  versionsArchived.json
Labels: approved, size/XS, lgtm

#574 Adjust Blog display date
  blog/release-v1.10/index.mdx
  blog/release-v1.11/index.mdx
  blog/release-v1.12/index.mdx
  blog/release-v1.13/index.mdx
  blog/release-v1.14/index.mdx
Labels: size/S, approved, lgtm

#582 Odd text color fix
  src/components/supporters/index.js
  src/components/supporters/index.scss
Labels: approved, size/XS, lgtm

#579 New Blog for Release KubeEdge v1.15
  blog/release-v1.15/index.mdx
Labels: approved, size/M, lgtm

#586 PR template update
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/XS, lgtm

#590 add inclusterconfig feature doc
  docs/advanced/inclusterconfig.md
  i18n/zh/docusaurus-plugin-content-docs/current/advanced/inclusterconfig.md
Labels: approved, size/L, lgtm

#572 add blog to explain how to enable Cilium with KubeEdge.
  blog/authors.yml
  blog/enable-cilium/images/overview.png
  blog/enable-cilium/index.mdx
  i18n/zh/docusaurus-plugin-content-blog/authors.yml
Labels: approved, size/L, lgtm
