Repository kubeedge/website, pull requests merged in 2024-09, with the labels that each got.

#624 Automated cherry pick of #623: update versions for 1.18
  versionsArchived.json
Labels: approved, size/XS, lgtm

#625 Automated cherry pick of #623: update versions for 1.18
  versionsArchived.json
Labels: approved, size/XS, lgtm

#626 Automated cherry pick of #623: update versions for 1.18
  versionsArchived.json
Labels: approved, size/XS, lgtm

#627 Automated cherry pick of #623: update versions for 1.18
  versionsArchived.json
Labels: approved, size/XS, lgtm

#635 add blog for release 1.18
  blog/release-v1.18/index.mdx
  i18n/zh/docusaurus-plugin-content-blog/release-v1.18/index.mdx
Labels: approved, size/L, lgtm

#600 Kubeedge Local Up Scirpt Guide
  docs/developer/local_up_kubeedge.md
Labels: approved, size/L, lgtm

#606 translate <delpoy-ha>/beehive from English to Chinese with help of chatgpt
  docs/architecture/beehive.md
  i18n/zh/docusaurus-plugin-content-docs/current/architecture/beehive.md
  i18n/zh/docusaurus-plugin-content-docs/current/setup/deploy-ha.md
Labels: approved, size/L, lgtm

#629 add chinese translation of ianvs/sendas with help of chatgpt
  docs/concept/ai/ianvs.md
  i18n/zh/docusaurus-plugin-content-docs/current/concept/ai/ianvs.md
  i18n/zh/docusaurus-plugin-content-docs/current/concept/ai/sedna.md
Labels: approved, size/L, lgtm

#628 Add script for cherry-pick
  hack/cherry_pick_pull.sh
Labels: approved, size/L, lgtm

#622 update the zh of devicetwin/metamanager/servicebus at edge components
  docs/architecture/edge/devicetwin.md
  docs/architecture/edge/metamanager.md
  i18n/zh/docusaurus-plugin-content-docs/current/architecture/edge/devicetwin.md
  i18n/zh/docusaurus-plugin-content-docs/current/architecture/edge/metamanager.md
  i18n/zh/docusaurus-plugin-content-docs/current/architecture/edge/servicebus.md
Labels: approved, size/L, lgtm

#616 update the zh of debug.md
  docs/advanced/debug.md
  i18n/zh/docusaurus-plugin-content-docs/current/advanced/debug.md
Labels: approved, size/M, lgtm

#615 Add Make Verify Script Guideline
  docs/developer/make_verify.md
Labels: approved, size/L, lgtm

#618 Update Cloud Architecture Chinese Version
  docs/architecture/cloud/device_controller.md
  i18n/zh/docusaurus-plugin-content-docs/current/architecture/cloud/device_controller.md
  i18n/zh/docusaurus-plugin-content-docs/current/architecture/cloud/edge_controller.md
Labels: approved, size/L, lgtm
