Repository kubeedge/website, pull requests merged in 2025-02, with the labels that each got.

#694 Add v1.20.0 release blog
  blog/release-v1.20/index.mdx
  functions/latestversion.js
  i18n/zh/docusaurus-plugin-content-blog/release-v1.20/index.mdx
Labels: approved, size/L, lgtm

#695 update docs version for v1.20.0
  versionsArchived.json
Labels: approved, size/XS, lgtm

#662 add how to install yarn via apt for Ubuntu users.
  README.md
Labels: approved, size/M, lgtm
