Repository kubeedge/website, pull requests merged in 2025-03, with the labels that each got.

#698 Automated cherry pick of #695: update docs version
  versionsArchived.json
Labels: approved, size/XS, lgtm

#696 Automated cherry pick of #695: update docs version
  versionsArchived.json
Labels: approved, size/XS, lgtm

#697 Automated cherry pick of #695: update docs version
  versionsArchived.json
Labels: approved, size/XS, lgtm

#672 fix: fixed X logo in dark mode and removed x.svg file
  src/css/custom.css
  static/img/x.svg
Labels: size/S, approved, lgtm

#661 remove redundant description for debug procedure, instead using link.
  docs/advanced/debug.md
  docs/setup/install-with-binary.md
  docs/setup/install-with-keadm.md
  i18n/zh/docusaurus-plugin-content-docs/current/advanced/debug.md
  i18n/zh/docusaurus-plugin-content-docs/current/setup/install-with-keadm.md
Labels: size/XL, approved, lgtm
